name: Build and Deploy
on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          echo "Installing python packages for docs..."
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx sphinx_rtd_theme breathe sphinxcontrib.bibtex docutils

      - name: Install and Build
        run: |
          cd Docs/sphinx_documentation
          echo "Build the Sphinx documentation for IAMR."
          make html

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'AMReX-Fluids/IAMR' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: Docs/sphinx_documentation/build/html # The folder the action should deploy.
          TARGET_FOLDER: docs_html # The folder the action should deploy to.
          CLEAN: false # Do not remove existing files from the deploy target.
